"""Generate the illustrated README and figure credits from canonical JSON.

Use --check in CI to detect stale generated outputs. No network or third-party
Python dependencies are needed.
"""

import argparse
import html
import json
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TYPE_LABELS = {"model_or_version": "Model / family", "method_or_system": "Method / system"}


def link(label, url):
    return f"[{label}]({url})"


def anchor(entry):
    return link(entry["name"], "#" + entry["slug"])


def badges(entry):
    items = []
    seen = set()
    for source in entry["technical_sources"]:
        url = source["url"]
        label = "Paper" if "arxiv.org" in url else "Technical source"
        if entry["id"] == 34 and "arxiv.org" in url:
            label = "Related encoding paper"
        if url not in seen:
            items.append(link(label, url))
            seen.add(url)
    for source in entry["official_entries"]:
        url = source["url"]
        if url in seen:
            continue
        label = "Code" if "github.com" in url else "Model" if "huggingface.co" in url else "Official project"
        if "model-studio" in url:
            label = "Hosted API"
        items.append(link(label, url))
        seen.add(url)
    return " · ".join(items)


def figure_caption(figure):
    if figure["kind"] == "editorial_schematic":
        return f"Editorial schematic based on {link('the primary source', figure['source_url'])}. {figure['simplification']}"
    label = "Official project diagram" if figure["kind"] == "project_figure" else f"Figure {figure['figure_number']}" if figure.get("figure_number") else "Author diagram"
    page = f", PDF page {figure['pdf_page']}" if figure.get("pdf_page") else ""
    return f"{label}{page}, from {link('the original source', figure['source_url'])}. {figure['display_caption']}"


def card(entry, figure):
    alt = html.escape(f"{entry['name']}: {figure['display_caption']}", quote=True)
    file = html.escape(figure["file"], quote=True)
    lines = [f'<a id="{entry["slug"]}"></a>', "", f'### {entry["name"]}', "", entry["summary"], "",
             badges(entry), "", f"**Authors:** {entry['authors']}  ",
             f"**First public date:** {entry['first_public_date']} ({entry['date_basis']})  ",
             f"**Contribution:** {', '.join(entry['contribution_type'])}", "",
             f'<p align="center"><a href="{file}"><img src="{file}" width="820" alt="{alt}" /></a></p>', "",
             "*" + figure_caption(figure) + "*", "",
             "<details>", "<summary>Architecture, temporal modeling, and training</summary>", "",
             "**Architecture.** " + entry["architecture"], "",
             "**Temporal modeling.** " + entry["temporal_modeling"], "",
             "**Training / inference recipe.** " + entry["training"], ""]
    if entry.get("datasets"):
        lines.extend(["**Data mentioned in the source:** " + ", ".join(entry["datasets"]) + ".", ""])
    if entry.get("version_note"):
        lines.extend(["**Version note.** " + entry["version_note"], ""])
    if entry.get("availability_note"):
        lines.extend(["**Availability.** " + entry["availability_note"], ""])
    sources = entry.get("primary_sources", [])
    sources = [source["url"] if isinstance(source, dict) else source for source in sources]
    if sources:
        lines.extend(["**Primary evidence:** " + " · ".join(link(f"Source {index + 1}", url) for index, url in enumerate(dict.fromkeys(sources))) + ".", ""])
    if figure.get("supplementary"):
        item = figure["supplementary"]
        lines.extend([link(item.get("link_label", "Additional author figure"), item["file"]) + " — " + link("source and attribution", item["source_url"]) + ".", ""])
    lines.extend(["</details>", "", "[Back to models](#models)", ""])
    return lines


def readme(catalog, figures):
    entries = catalog["entries"]
    models = [entry for entry in entries if entry["record_type"] == "model_or_version"]
    methods = [entry for entry in entries if entry["record_type"] == "method_or_system"]
    counts = Counter(figure["kind"] for figure in figures.values())
    original = sum(count for kind, count in counts.items() if kind != "editorial_schematic")
    lines = ["<!-- Generated by scripts/build_readme.py; edit data/architectures.json and the figure manifest. -->", "",
             "# Awesome Video MLLM Architectures", "",
             "![Awesome Video MLLM Architectures](assets/banner.svg)", "",
             "An illustrated collection of video multimodal large language models: how frames become visual tokens, how temporal evidence reaches the language decoder, and how long or live video is kept in memory.", "",
             f"**{len(entries)} illustrated records** · {len(models)} model/version/family cards · {len(methods)} method/system cards · reviewed through **{catalog['research_cutoff']}**.", "",
             f"Every card includes a local diagram, architecture explanation, temporal mechanism, training or inference recipe, and primary sources. Primary diagrams comprise {original} author figures and {counts['editorial_schematic']} explicitly labeled editorial schematics. A family or training recipe can share an existing backbone; record count is not a count of independent architectures.", "",
             "The organization is inspired by [Awesome VLM Architectures](https://github.com/gokayfem/awesome-vlm-architectures). Descriptions are newly written and figure provenance is recorded. The initial Chinese research is preserved in [RESEARCH.zh-CN.md](RESEARCH.zh-CN.md).", "",
             "## Contents", "",
             "- [Models](#models)", "- [Reading routes](#reading-routes)", "- [Release timeline](#release-timeline)",
             "- [Model architectures](#model-architectures)", "- [Methods and systems](#methods-and-systems)",
             "- [Discovery sources](#discovery-sources)", "- [Citation and reuse](#citation-and-reuse)",
             "- [Contributing](CONTRIBUTING.md)", "", "## Models", "",
             "Models are grouped by the verified first-public date. Later milestones of a family are explained in its card. Methods are indexed separately below.", ""]
    years = sorted({entry["first_public_date"][:4] for entry in models}, reverse=True)
    for year in years:
        group = sorted([entry for entry in models if entry["first_public_date"].startswith(year)], key=lambda entry: entry["first_public_date"], reverse=True)
        lines.extend(["<details open>" if year == years[0] else "<details>", f"<summary>{year} ({len(group)} records)</summary>", ""])
        lines.extend("- " + anchor(entry) for entry in group)
        lines.extend(["", "</details>", ""])
    lines.extend(["**Methods and systems:** " + " · ".join(anchor(entry) for entry in methods) + ".", "", "## Reading routes", "",
                  "Use these routes to compare mechanisms. Categories describe the main reading focus; capabilities can overlap.", "",
                  "| Route | What to compare | Cards |", "| --- | --- | --- |"])
    for category in catalog["categories"]:
        group = [entry for entry in entries if entry["category"] == category["id"]]
        lines.append(f"| {category['label']} | {category['description']} | " + ", ".join(anchor(entry) for entry in group) + " |")
    lines.extend(["", "## Release timeline", "",
                  "Dates follow the evidence basis shown in each card: arXiv v1 submission or a dated official release. Family milestones and later paper revisions do not create duplicate rows.", "",
                  "| First public date | Record | Type | Main contribution |", "| --- | --- | --- | --- |"])
    ordered = sorted(entries, key=lambda entry: (entry["first_public_date"], entry["id"]), reverse=True)
    for entry in ordered:
        lines.append(f"| {entry['first_public_date']} | {anchor(entry)} | {TYPE_LABELS[entry['record_type']]} | " + ", ".join(entry["contribution_type"]) + " |")
    lines.extend(["", "## Model architectures", "",
                  "Cards appear from newest to oldest. Click a diagram to view the original local asset at full size. The expandable section explains the architecture and distinguishes structural changes from data or training contributions.", ""])
    for entry in ordered:
        if entry["record_type"] == "model_or_version":
            lines.extend(card(entry, figures[entry["id"]]))
    lines.extend(["## Methods and systems", "",
                  "These records describe cache retrieval, token reduction, grounding refinement, or an agent/memory system around an existing model. Their diagrams identify where the method acts.", ""])
    for entry in ordered:
        if entry["record_type"] == "method_or_system":
            lines.extend(card(entry, figures[entry["id"]]))
    lines.extend(["## Discovery sources", "",
                  "The first survey audited 15 awesome repositories and extracted 153 name-level candidates from five core lists. The illustrated cards were selected and checked against primary technical sources; discovery-list inclusion alone does not establish architecture or video support.", "",
                  "- [Audited awesome repositories and candidate extraction](docs/source-audit.md)",
                  "- [Reference repository: structure and README analysis](docs/reference-repository-analysis.md)",
                  "- [Scope, taxonomy, dates, and availability policy](docs/curation-policy.md)",
                  "- [Original Chinese research snapshot](RESEARCH.zh-CN.md)",
                  "- [Machine-readable architecture catalog](data/architectures.json)",
                  "- [Figure credits](assets/architectures/CREDITS.md) and [figure rights notice](assets/architectures/FIGURE_NOTICE.md)", "",
                  "## Citation and reuse", "",
                  "Cite each original paper when discussing its model. Use [CITATION.cff](CITATION.cff) when referring to this collection's curation or editorial diagrams.", "",
                  "Original text, scripts and editorial schematics are dedicated under [CC0-1.0](LICENSE). Third-party paper and project figures retain their original rights and are excluded from that dedication; see the [figure notice](assets/architectures/FIGURE_NOTICE.md).", "",
                  "To update the collection, edit the canonical JSON, regenerate the README, and run the checks described in [CONTRIBUTING.md](CONTRIBUTING.md)."])
    return "\n".join(lines) + "\n"


def credits(catalog, figures):
    names = {entry["id"]: entry["name"] for entry in catalog["entries"]}
    lines = ["<!-- Generated by scripts/build_readme.py. -->", "", "# Architecture figure credits", "",
             "Author figures retain their original rights. Editorial schematics are marked explicitly. See [FIGURE_NOTICE.md](FIGURE_NOTICE.md). Figure numbers follow the linked version; PDF pages are one-based.", "",
             "| ID | Record / local image | Kind | Primary source | Figure / PDF page | Extraction or redraw note |",
             "| --- | --- | --- | --- | --- | --- |"]
    for entry_id, figure in sorted(figures.items()):
        filename = Path(figure["file"]).name
        kind = figure["kind"].replace("_", " ")
        source = link("Primary source", figure["source_url"])
        location = f"Fig. {figure['figure_number']}" if figure.get("figure_number") else "—"
        if figure.get("pdf_page"):
            location += f" / p. {figure['pdf_page']}"
        note = link("Extraction source", figure["extraction_source"]) if figure.get("extraction_source") else figure.get("simplification", "Downloaded from author HTML or cropped from the primary PDF.")
        lines.append(f"| {entry_id:02d} | {link(names[entry_id], filename)} | {kind} | {source} | {location} | {note} |")
        if figure.get("supplementary"):
            item = figure["supplementary"]
            lines.append(f"| {entry_id:02d} (extra) | {link(names[entry_id] + ' temporal mechanism', Path(item['file']).name)} | {item['kind'].replace('_', ' ')} | {link('Primary source', item['source_url'])} | Fig. {item.get('figure_number', '—')} | {link('Extraction source', item['extraction_source']) if item.get('extraction_source') else 'Author figure.'} |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    catalog = json.loads((ROOT / "data/architectures.json").read_text(encoding="utf-8"))
    manifest = json.loads((ROOT / "assets/architectures/manifest.json").read_text(encoding="utf-8"))
    figures = {figure["id"]: figure for figure in manifest["figures"]}
    outputs = {ROOT / "README.md": readme(catalog, figures), ROOT / "assets/architectures/CREDITS.md": credits(catalog, figures)}
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Generated file is stale: {path.relative_to(ROOT)}")
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    print("Generated files are current." if args.check else "Built README.md and figure credits.")


if __name__ == "__main__":
    main()
